### ISSUE TITLE
ValueError: 42170 is not a valid ChainID

### ISSUE THREAD

**Issue by positonic** [coinyon/buchfink#2]
I'm pretty stumped trying to run buckfink, and idea what's wrong?:

<img width="1197" alt="image" src="https://github.com/coinyon/buchfink/assets/10499048/e429f0c5-0612-4baa-835e-d8027b79ef5c">

**Comment by coinyon** [comment]
Hmm haven't seen this error before. Make sure you did install the rotki version specified in "requirements.txt"

**Comment by coinyon** [comment]
I get the same error now. It is probably due to a rotki asset update for an unsupported version. I currently don't have the time to update Buchfink to use latest Rotki version. Sorry. Will try to find the time to work on this in the coming weeks.

**Comment by positonic** [comment]
I understand, thanks for your work!

**Comment by coinyon** [comment]
This should be solved now by upgrading the Rotki dependency and adapting alot of stuff. In the meantime Rotki moved to Python 3.11 so you probably need to setup your local env again.

Please re-open if the problem persists.
